from google.cloud import bigquery
import pandas as pd

def bigquery_connector(query:str=None)->pd.DataFrame:
    '''
    Sends a SQL query to the BigQuery connection, and returns the results as a DataFrame
        
        Args:
            query (str): The query to be sent to BigQuery
        Returns:
            df (pandas DataFrame): The dataframe generated by the query
    
    '''
    client = bigquery.Client()
    df = client.query(query).to_dataframe()
    return df
